"use client";
import { Activity, ArrowDownRight, ArrowUpRight, Bot, CheckCircle2, CircleAlert, CircleDollarSign, Clock3, CreditCard, FolderKanban, ShieldAlert, Users } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

export function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="admin-eyebrow">{eyebrow}</p><h1 className="admin-title">{title}</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">{description}</p></div>{action}</div>; }
const kpiIcons = { revenue: CircleDollarSign, users: Users, projects: FolderKanban, bot: Bot, card: CreditCard, alert: ShieldAlert };
export function KpiCard({ label, value, change, icon, accent = "cyan" }: { label: string; value: string; change: string; icon: keyof typeof kpiIcons; accent?: "cyan" | "violet" | "orange" | "green" }) { const Icon = kpiIcons[icon]; return <div className="admin-card relative overflow-hidden"><div className={`admin-kpi-glow bg-${accent === "cyan" ? "cyan" : accent === "violet" ? "violet" : accent === "orange" ? "orange" : "emerald"}-400/10`}/><div className="flex items-start justify-between"><div><p className="text-xs text-slate-400">{label}</p><p className="mt-3 font-[var(--font-heading)] text-2xl font-semibold tracking-tight">{value}</p><p className={`mt-2 flex items-center gap-1 text-[11px] ${change.startsWith("-") ? "text-rose-300" : "text-emerald-300"}`}>{change.startsWith("-") ? <ArrowDownRight size={13}/> : <ArrowUpRight size={13}/>} {change} <span className="text-slate-600">vs. mês anterior</span></p></div><span className={`grid h-9 w-9 place-items-center rounded-xl ${accent === "cyan" ? "bg-cyan-400/10 text-cyan-300" : accent === "violet" ? "bg-violet-400/10 text-violet-300" : accent === "orange" ? "bg-orange-400/10 text-orange-300" : "bg-emerald-400/10 text-emerald-300"}`}><Icon size={18}/></span></div></div>; }
export function StatusBadge({ status }: { status: string }) { const success = ["Ativo", "Pago", "Sucesso", "Entregue"].includes(status); const warn = ["Em negociação", "QA", "Design"].includes(status); return <span className={`admin-badge ${success ? "admin-badge-success" : warn ? "admin-badge-warn" : "admin-badge-muted"}`}>{success ? <CheckCircle2 size={12}/> : warn ? <Clock3 size={12}/> : <CircleAlert size={12}/>} {status}</span>; }
export function RevenueChart({ data }: { data: { month: string; value: number }[] }) { return <div className="h-[285px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 8, right: 8, left: -18, bottom: 0 }}><defs><linearGradient id="revenueGradient" x1="0" y1="0" x2="1" y2="0"><stop offset="0%" stopColor="#00f0ff"/><stop offset="100%" stopColor="#8b5cf6"/></linearGradient><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#00f0ff" stopOpacity={.28}/><stop offset="100%" stopColor="#8b5cf6" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="rgba(255,255,255,.06)" vertical={false}/><XAxis dataKey="month" tick={{ fill: "#64748b", fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis tick={{ fill: "#64748b", fontSize: 10 }} axisLine={false} tickLine={false} tickFormatter={v => `R$${v / 1000}k`}/><Tooltip contentStyle={{ background: "#101024", border: "1px solid rgba(255,255,255,.12)", borderRadius: 12, color: "#e8e8f0", fontSize: 12 }} formatter={(value) => [`R$ ${Number(value).toLocaleString("pt-BR")}`, "Faturamento"]}/><Area type="monotone" dataKey="value" stroke="url(#revenueGradient)" strokeWidth={2.5} fill="url(#revenueFill)"/></AreaChart></ResponsiveContainer></div>; }
export function SectionTitle({ title, meta }: { title: string; meta?: string }) { return <div className="mb-5 flex items-center justify-between"><h2 className="font-[var(--font-heading)] text-lg font-medium">{title}</h2>{meta && <span className="text-xs text-slate-500">{meta}</span>}</div>; }
