"use client";

import { useState } from "react";
import { Check, ChevronRight, Plus, RefreshCw } from "lucide-react";
import type { CommercialSnapshot } from "@/lib/commercial-types";

type Props = { initial: CommercialSnapshot };

async function post(payload: Record<string, unknown>) {
  const response = await fetch("/api/admin/commercial", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error ?? "Operação não concluída.");
}

function DialogForm({ title, onClose, children, onSubmit, submitLabel = "Salvar" }: { title: string; onClose: () => void; children: React.ReactNode; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void; submitLabel?: string }) {
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4" role="dialog" aria-modal="true"><form onSubmit={onSubmit} className="w-full max-w-lg rounded-2xl border border-white/10 bg-[#0d0d20] p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="font-[var(--font-heading)] text-lg">{title}</h2><button type="button" onClick={onClose} className="text-sm text-slate-500 hover:text-white">Fechar</button></div><div className="grid gap-3">{children}</div><button className="mt-5 w-full rounded-xl bg-cyan-300 px-4 py-3 text-sm font-semibold text-[#050510] hover:bg-cyan-200">{submitLabel}</button></form></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1 text-xs text-slate-400">{label}{children}</label>; }
function Input(props: React.InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className="rounded-lg border border-white/10 bg-white/[.04] px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-300/60" />; }
function Select(props: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select {...props} className="rounded-lg border border-white/10 bg-[#15152a] px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-300/60" />; }

export function CommercialWorkspace({ initial }: Props) {
  const [data, setData] = useState(initial);
  const [modal, setModal] = useState<"company" | "contact" | "deal" | "task" | "edit-deal" | null>(null);
  const [selectedDeal, setSelectedDeal] = useState<CommercialSnapshot["deals"][number] | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [refreshing, setRefreshing] = useState(false);

  async function refresh() {
    setRefreshing(true); setError("");
    try { const response = await fetch("/api/admin/commercial"); if (!response.ok) throw new Error("A atualização falhou."); setData(await response.json()); } catch (cause) { setError(cause instanceof Error ? cause.message : "A atualização falhou."); } finally { setRefreshing(false); }
  }
  async function run(action: () => Promise<void>) { setBusy(true); setError(""); try { await action(); setModal(null); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível concluir."); } finally { setBusy(false); } }

  return <div className="space-y-6">
    {error && <div role="alert" className="rounded-xl border border-rose-400/30 bg-rose-400/10 px-4 py-3 text-sm text-rose-200">{error}</div>}
    <div className="flex flex-wrap gap-2"><button onClick={() => setModal("company")} className="admin-primary-btn"><Plus size={15}/> Empresa</button><button onClick={() => setModal("contact")} className="admin-secondary-btn"><Plus size={15}/> Contato</button><button onClick={() => setModal("deal")} className="admin-secondary-btn"><Plus size={15}/> Negócio</button><button onClick={() => setModal("task")} className="admin-secondary-btn"><Plus size={15}/> Tarefa</button><button onClick={refresh} disabled={refreshing} className="admin-icon-btn" aria-label="Atualizar"><RefreshCw size={16} className={refreshing ? "animate-spin" : ""}/></button></div>

    <section className="grid gap-4 sm:grid-cols-3"><div className="admin-mini-stat"><span>Empresas</span><strong>{data.companies.length}</strong><small>Workspace atual</small></div><div className="admin-mini-stat"><span>Negócios abertos</span><strong>{data.deals.filter((deal) => deal.status === "open").length}</strong><small>Pipeline comercial</small></div><div className="admin-mini-stat"><span>Tarefas abertas</span><strong>{data.tasks.filter((task) => task.status === "open").length}</strong><small>Próximas ações</small></div></section>

    <section className="admin-card"><div className="mb-5 flex items-center justify-between"><div><p className="admin-eyebrow">Sales pipeline</p><h2 className="font-[var(--font-heading)] text-lg">Negócios</h2></div><span className="text-xs text-slate-500">{data.deals.length} registros reais</span></div><div className="grid gap-3 overflow-x-auto pb-2 md:grid-cols-2 xl:grid-cols-4">{(data.pipelines[0]?.stages ?? []).map((stage) => <div key={stage.id} className="min-w-[220px] rounded-xl border border-white/[.07] bg-white/[.02] p-3"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-medium text-slate-300">{stage.name}</span><span className="text-[10px] text-slate-600">{stage.probability}%</span></div><div className="grid gap-2">{data.deals.filter((deal) => deal.stageId === stage.id).map((deal) => <article key={deal.id} className="rounded-lg border border-white/[.07] bg-[#111126] p-3"><p className="text-sm font-medium text-white">{deal.title}</p><p className="mt-1 text-xs text-slate-500">{deal.companyName} · R$ {(deal.amountCents / 100).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}</p><button type="button" onClick={() => { setSelectedDeal(deal); setModal("edit-deal"); }} className="mt-2 text-[11px] text-cyan-300 hover:text-cyan-200">Editar negócio</button><Select aria-label={`Mover ${deal.title}`} value={deal.stageId} onChange={(event) => void run(() => post({ action: "deal.move", dealId: deal.id, stageId: event.target.value }))} className="mt-3 w-full text-xs"><option value={deal.stageId}>{stage.name}</option>{(data.pipelines[0]?.stages ?? []).filter((next) => next.id !== stage.id).map((next) => <option key={next.id} value={next.id}>{next.name}</option>)}</Select></article>)}</div></div>)}</div></section>

    <div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><section className="admin-card"><div className="mb-4 flex items-center justify-between"><h2 className="font-[var(--font-heading)] text-lg">Tarefas</h2><span className="text-xs text-slate-500">{data.tasks.length}</span></div><div className="grid gap-2">{data.tasks.map((task) => <label key={task.id} className="flex items-center gap-3 rounded-lg border border-white/[.06] p-3"><input type="checkbox" checked={task.status === "done"} onChange={(event) => void run(() => post({ action: "task.toggle", taskId: task.id, done: event.target.checked }))} className="accent-cyan-300"/><span className={task.status === "done" ? "text-sm text-slate-600 line-through" : "text-sm text-slate-200"}>{task.title}<small className="mt-1 block text-xs text-slate-500">{task.companyName || "Sem empresa"}{task.dueDate ? ` · ${task.dueDate}` : ""}</small></span>{task.status === "done" && <Check size={15} className="ml-auto text-emerald-300"/>}</label>)}{data.tasks.length === 0 && <p className="text-sm text-slate-500">Nenhuma tarefa cadastrada.</p>}</div></section><section className="admin-card"><div className="mb-4 flex items-center justify-between"><h2 className="font-[var(--font-heading)] text-lg">Timeline</h2><span className="text-xs text-slate-500">Atividade comercial</span></div><div className="grid gap-3">{data.activities.map((activity) => <div key={activity.id} className="flex gap-3 border-l border-cyan-300/30 pl-3"><div><p className="text-sm text-slate-300">{activity.body}</p><p className="mt-1 text-[11px] text-slate-600">{activity.companyName}{activity.dealTitle ? ` · ${activity.dealTitle}` : ""} · {new Date(activity.createdAt).toLocaleString("pt-BR")}</p></div><ChevronRight size={14} className="ml-auto shrink-0 text-slate-700"/></div>)}{data.activities.length === 0 && <p className="text-sm text-slate-500">A timeline aparece após a primeira atividade.</p>}</div></section></div>

    {modal === "company" && <DialogForm title="Nova empresa" onClose={() => setModal(null)} onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void run(() => post({ action: "company.create", name: form.get("name") })); }}><Field label="Nome"><Input name="name" required autoFocus placeholder="Empresa" /></Field><Field label="Segmento"><Input name="industry" placeholder="Tecnologia" /></Field><Field label="Website"><Input name="website" type="url" placeholder="https://" /></Field></DialogForm>}
    {modal === "contact" && <DialogForm title="Novo contato" onClose={() => setModal(null)} onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void run(() => post({ action: "contact.create", companyId: form.get("companyId"), name: form.get("name"), email: form.get("email") })); }}><Field label="Empresa"><Select name="companyId" required><option value="">Selecione</option>{data.companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</Select></Field><Field label="Nome"><Input name="name" required autoFocus placeholder="Nome do contato" /></Field><Field label="Email"><Input name="email" type="email" placeholder="email@empresa.com" /></Field></DialogForm>}
    {modal === "deal" && <DialogForm title="Novo negócio" onClose={() => setModal(null)} onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void run(() => post({ action: "deal.create", title: form.get("title"), companyId: form.get("companyId"), pipelineId: form.get("pipelineId"), stageId: form.get("stageId"), amountCents: Math.round(Number(form.get("amount") || 0) * 100) })); }}><Field label="Título"><Input name="title" required autoFocus placeholder="Redesign do site" /></Field><Field label="Empresa"><Select name="companyId" required><option value="">Selecione</option>{data.companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</Select></Field><Field label="Pipeline / etapa"><Select name="pipelineId" required>{data.pipelines.map((pipeline) => <option key={pipeline.id} value={pipeline.id}>{pipeline.name}</option>)}</Select><Select name="stageId" required>{(data.pipelines[0]?.stages ?? []).map((stage) => <option key={stage.id} value={stage.id}>{stage.name}</option>)}</Select></Field><Field label="Valor (R$)"><Input name="amount" type="number" min="0" step="0.01" /></Field></DialogForm>}
    {modal === "edit-deal" && selectedDeal && <DialogForm title="Editar negócio" onClose={() => { setModal(null); setSelectedDeal(null); }} onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void run(() => post({ action: "deal.update", dealId: selectedDeal.id, title: form.get("title"), amountCents: Math.round(Number(form.get("amount") || 0) * 100) })); }}><Field label="Título"><Input name="title" required autoFocus defaultValue={selectedDeal.title} /></Field><Field label="Valor (R$)"><Input name="amount" type="number" min="0" step="0.01" defaultValue={(selectedDeal.amountCents / 100).toFixed(2)} /></Field></DialogForm>}
    {modal === "task" && <DialogForm title="Nova tarefa" onClose={() => setModal(null)} onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void run(() => post({ action: "task.create", title: form.get("title"), companyId: form.get("companyId") || undefined, dueDate: form.get("dueDate") || undefined, priority: form.get("priority") })); }}><Field label="Título"><Input name="title" required autoFocus placeholder="Fazer follow-up" /></Field><Field label="Empresa (opcional)"><Select name="companyId"><option value="">Sem empresa</option>{data.companies.map((company) => <option key={company.id} value={company.id}>{company.name}</option>)}</Select></Field><Field label="Prazo"><Input name="dueDate" type="date" /></Field><Field label="Prioridade"><Select name="priority"><option value="medium">Média</option><option value="high">Alta</option><option value="low">Baixa</option></Select></Field></DialogForm>}
    {busy && <div className="fixed bottom-5 right-5 rounded-xl border border-cyan-300/30 bg-[#101024] px-4 py-3 text-xs text-cyan-200">Salvando…</div>}
  </div>;
}
