"use client";

import { useState } from "react";
import { Check, MessageSquare, Plus, RefreshCw, Send, Ticket, UserRound } from "lucide-react";
import type { InboxSnapshot } from "@/lib/inbox-types";

type Props = { initial: InboxSnapshot; currentUserId: string };
async function post(payload: Record<string, unknown>) { const response = await fetch("/api/admin/inbox", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error ?? "Operação não concluída."); return body; }
function statusLabel(status: string) { return status === "resolved" ? "Resolvido" : status === "pending" ? "Pendente" : "Aberto"; }
function priorityClass(priority: string) { return priority === "urgent" ? "text-destructive" : priority === "high" ? "text-warning" : "text-muted-foreground"; }

export function InboxWorkspace({ initial, currentUserId }: Props) {
  const [data, setData] = useState(initial);
  const [selectedId, setSelectedId] = useState(initial.conversations[0]?.id ?? null);
  const [filter, setFilter] = useState<"all" | "open" | "resolved">("all");
  const [draft, setDraft] = useState("");
  const [internalNote, setInternalNote] = useState(false);
  const [ticketTitle, setTicketTitle] = useState("");
  const [ticketPriority, setTicketPriority] = useState("normal");
  const [ticketOpen, setTicketOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const selected = data.conversations.find((conversation) => conversation.id === selectedId) ?? null;
  const visible = data.conversations.filter((conversation) => filter === "all" || conversation.status === filter);

  async function refresh() { setBusy(true); setError(""); try { const response = await fetch("/api/admin/inbox"); const next = await response.json(); if (!response.ok) throw new Error(next.error); setData(next); } catch (cause) { setError(cause instanceof Error ? cause.message : "Falha ao atualizar."); } finally { setBusy(false); } }
  async function run(action: () => Promise<unknown>) { setBusy(true); setError(""); try { await action(); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Operação não concluída."); } finally { setBusy(false); } }
  async function send() { if (!selected || !draft.trim()) return; await run(async () => { await post({ action: "message.send", conversationId: selected.id, body: draft, internalNote }); setDraft(""); }); }

  return <div className="space-y-5">
    {error && <div role="alert" className="rounded-xl border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>}
    <div className="flex flex-wrap items-center gap-2"><button onClick={() => setTicketOpen(true)} className="admin-primary-btn"><Plus size={15}/> Novo ticket</button><button onClick={refresh} className="admin-icon-btn" aria-label="Atualizar Inbox"><RefreshCw size={16} className={busy ? "animate-spin" : ""}/></button><div className="ml-auto flex rounded-lg border border-border p-1">{(["all", "open", "resolved"] as const).map((value) => <button key={value} onClick={() => setFilter(value)} className={`rounded-md px-3 py-1.5 text-xs ${filter === value ? "bg-primary text-primary-foreground" : "text-muted-foreground"}`}>{value === "all" ? "Todos" : value === "open" ? "Abertos" : "Resolvidos"}</button>)}</div></div>
    <div className="grid min-h-[560px] overflow-hidden rounded-2xl border border-border bg-card lg:grid-cols-[300px_1fr]">
      <aside className="border-b border-border lg:border-b-0 lg:border-r"><div className="border-b border-border p-4"><p className="admin-eyebrow">Inbox</p><h2 className="font-heading text-lg">Conversas</h2><p className="mt-1 text-xs text-muted-foreground">{visible.length} no workspace atual</p></div><div className="max-h-[480px] overflow-y-auto">{visible.map((conversation) => <button key={conversation.id} onClick={() => setSelectedId(conversation.id)} className={`w-full border-b border-border p-4 text-left hover:bg-muted ${selectedId === conversation.id ? "bg-primary/10" : ""}`}><div className="flex items-start justify-between gap-2"><span className="truncate text-sm text-foreground">{conversation.subject || "Sem assunto"}</span><span className={`text-[10px] ${priorityClass(conversation.priority)}`}>{conversation.priority}</span></div><p className="mt-1 truncate text-xs text-muted-foreground">{conversation.companyName} · {conversation.contactName}</p><span className="mt-2 inline-block text-[10px] text-muted-foreground">{statusLabel(conversation.status)}</span></button>)}{visible.length === 0 && <div className="p-5 text-sm text-muted-foreground">Nenhuma conversa neste filtro.</div>}</div></aside>
      <section className="flex min-w-0 flex-col">{selected ? <><header className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-5"><div><p className="text-xs text-muted-foreground">{selected.companyName} · {selected.contactName}</p><h2 className="mt-1 font-heading text-xl">{selected.subject || "Sem assunto"}</h2></div><div className="flex gap-2"><button onClick={() => void run(() => post({ action: "conversation.update", conversationId: selected.id, assigneeId: selected.assigneeId === currentUserId ? null : currentUserId }))} className="admin-secondary-btn"><UserRound size={14}/>{selected.assigneeId === currentUserId ? "Desatribuir" : "Atribuir a mim"}</button><button onClick={() => void run(() => post({ action: "conversation.update", conversationId: selected.id, status: selected.status === "resolved" ? "open" : "resolved" }))} className="admin-secondary-btn"><Check size={14}/>{selected.status === "resolved" ? "Reabrir" : "Resolver"}</button></div></header><div className="flex-1 space-y-4 overflow-y-auto p-5">{selected.messages.map((message) => <div key={message.id} className={`max-w-[88%] rounded-xl border p-3 ${message.messageType === "internal_note" ? "border-warning/20 bg-warning/6" : "border-border bg-muted"}`}><p className="mb-1 text-[10px] uppercase tracking-widest text-muted-foreground">{message.messageType === "internal_note" ? "Nota interna" : "Mensagem"} · {new Date(message.createdAt).toLocaleString("pt-BR")}</p><p className="whitespace-pre-wrap text-sm text-foreground">{message.body}</p></div>)}{selected.messages.length === 0 && <div className="grid h-full place-items-center text-sm text-muted-foreground">Nenhuma mensagem nesta conversa.</div>}</div><footer className="border-t border-border p-4"><div className="flex items-center gap-2"><input value={draft} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); void send(); } }} placeholder={internalNote ? "Escreva uma nota interna…" : "Escreva uma resposta…"} className="min-w-0 flex-1 rounded-lg border border-border bg-muted px-3 py-2.5 text-sm text-foreground outline-none focus:border-primary/60"/><button onClick={() => void send()} disabled={!draft.trim() || busy} className="grid h-10 w-10 place-items-center rounded-lg bg-primary text-primary-foreground disabled:opacity-40" aria-label="Enviar"><Send size={16}/></button></div><label className="mt-2 flex items-center gap-2 text-xs text-muted-foreground"><input type="checkbox" checked={internalNote} onChange={(event) => setInternalNote(event.target.checked)} className="accent-primary"/> Nota interna</label></footer></> : <div className="grid flex-1 place-items-center p-6 text-center"><MessageSquare className="mb-3 text-muted-foreground"/><p className="text-sm text-muted-foreground">Selecione uma conversa ou aguarde uma nova entrada.</p></div>}</section>
    </div>
    <section className="admin-card"><div className="mb-4 flex items-center justify-between"><div><p className="admin-eyebrow">Support desk</p><h2 className="font-heading text-lg">Tickets</h2></div><Ticket size={18} className="text-accent"/></div>{data.tickets.length === 0 ? <p className="text-sm text-muted-foreground">Nenhum ticket criado neste workspace.</p> : <div className="grid gap-2">{data.tickets.map((ticket) => <div key={ticket.id} className="flex flex-wrap items-center gap-3 rounded-lg border border-border p-3"><Ticket size={15} className="text-muted-foreground"/><span className="min-w-[180px] flex-1 text-sm text-foreground">{ticket.title}</span><span className={`text-xs ${priorityClass(ticket.priority)}`}>{ticket.priority}</span><button onClick={() => void run(() => post({ action: "ticket.update", ticketId: ticket.id, status: ticket.status === "resolved" ? "open" : "resolved" }))} className="admin-secondary-btn text-xs">{ticket.status === "resolved" ? "Reabrir" : "Resolver"}</button></div>)}</div>}</section>
    {ticketOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-overlay p-4"><form onSubmit={(event) => { event.preventDefault(); void run(async () => { await post({ action: "ticket.create", title: ticketTitle, priority: ticketPriority }); setTicketTitle(""); setTicketOpen(false); }); }} className="w-full max-w-md rounded-2xl border border-border bg-popover p-6"><div className="mb-5 flex justify-between"><h2 className="font-heading text-lg">Novo ticket</h2><button type="button" onClick={() => setTicketOpen(false)} className="text-sm text-muted-foreground">Fechar</button></div><label className="grid gap-2 text-xs text-muted-foreground">Título<input required value={ticketTitle} onChange={(event) => setTicketTitle(event.target.value)} maxLength={180} className="rounded-lg border border-border bg-muted px-3 py-2.5 text-sm text-foreground"/></label><label className="mt-3 grid gap-2 text-xs text-muted-foreground">Prioridade<select value={ticketPriority} onChange={(event) => setTicketPriority(event.target.value)} className="rounded-lg border border-border bg-card px-3 py-2.5 text-sm text-foreground"><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><button className="mt-5 w-full rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground">Criar ticket</button></form></div>}
  </div>;
}
