"use client";

import { useState } from "react";
import type { PaymentLinkAction } from "@/lib/payment-link-validation";
import { parseCurrencyToCents } from "@/lib/payment-link-format";

type Option = { id: string; name: string };
type Props = { clients: Option[]; deals: Option[]; onSubmit: (input: PaymentLinkAction) => Promise<void>; onCancel: () => void };

export function PaymentLinkForm({ clients, deals, onSubmit, onCancel }: Props) {
  const [kind, setKind] = useState<"one_time" | "recurring">("one_time");
  const [amount, setAmount] = useState(""); const [description, setDescription] = useState(""); const [interval, setInterval] = useState<"month" | "year">("month"); const [installments, setInstallments] = useState("1"); const [clientId, setClientId] = useState(""); const [dealId, setDealId] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); try { await onSubmit({ action: "payment-link.create", kind, amountCents: parseCurrencyToCents(amount), currency: "brl", description, recurringInterval: kind === "recurring" ? interval : undefined, installments: kind === "one_time" ? Number(installments) : 1, clientId: clientId || undefined, dealId: dealId || undefined }); } finally { setSaving(false); } }
  return <form onSubmit={submit} className="mt-5 grid gap-3 rounded-xl border border-white/[.08] bg-white/[.02] p-4 md:grid-cols-2"><label className="text-xs text-slate-400">Tipo<select value={kind} onChange={(event) => setKind(event.target.value as "one_time" | "recurring")} className="admin-input mt-1"><option value="one_time">Projeto avulso</option><option value="recurring">Recorrência</option></select></label><label className="text-xs text-slate-400">Valor total/mensal<input required value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="R$ 1.500,00" className="admin-input mt-1"/></label>{kind === "recurring" ? <label className="text-xs text-slate-400">Periodicidade<select value={interval} onChange={(event) => setInterval(event.target.value as "month" | "year")} className="admin-input mt-1"><option value="month">Mensal</option><option value="year">Anual</option></select></label> : <label className="text-xs text-slate-400">Parcelamento habilitado<select value={installments} onChange={(event) => setInstallments(event.target.value)} className="admin-input mt-1"><option value="1">À vista</option><option value="2">Até 2x</option><option value="3">Até 3x</option><option value="6">Até 6x</option><option value="12">Até 12x</option></select></label>}<label className="text-xs text-slate-400 md:col-span-2">Descrição<input required maxLength={240} value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Landing page — projeto completo" className="admin-input mt-1"/></label><label className="text-xs text-slate-400">Cliente (opcional)<select value={clientId} onChange={(event) => setClientId(event.target.value)} className="admin-input mt-1"><option value="">Nenhum</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label className="text-xs text-slate-400">Negócio (opcional)<select value={dealId} onChange={(event) => setDealId(event.target.value)} className="admin-input mt-1"><option value="">Nenhum</option>{deals.map((deal) => <option key={deal.id} value={deal.id}>{deal.name}</option>)}</select></label><p className="text-[11px] text-slate-500 md:col-span-2">O Stripe será a autoridade do preço. O navegador envia apenas os dados do formulário; a criação acontece no servidor.</p><div className="flex gap-2 md:col-span-2"><button disabled={saving} className="admin-primary-btn">{saving ? "Criando…" : "Criar Payment Link"}</button><button type="button" onClick={onCancel} className="admin-secondary-btn">Cancelar</button></div></form>;
}
