"use client";

import { useState } from "react";
import { Check, Edit3, Plus, RefreshCw, Target, Trophy } from "lucide-react";
import type { PerformanceGoal, PerformanceMetric, PerformanceSnapshot } from "@/lib/performance-types";

const metricLabels: Record<PerformanceMetric, string> = { revenue_cents: "Receita", deals_won: "Negócios ganhos", tasks_completed: "Tarefas concluídas", messages_sent: "Mensagens enviadas" };
const valueLabel = (metric: PerformanceMetric, value: number) => metric === "revenue_cents" ? new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value / 100) : String(value);
async function post(payload: Record<string, unknown>) { const response = await fetch("/api/admin/performance", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error ?? "Operação não concluída."); }
function ProgressBar({ metric, value, target }: { metric: PerformanceMetric; value: number; target: number }) { const percentage = target > 0 ? Math.min(100, Math.round((value / target) * 100)) : 0; return <div className="mt-3"><div className="mb-1 flex justify-between text-[11px] text-slate-500"><span>{valueLabel(metric, value)}</span><span>{percentage}%</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/[.07]"><div className="h-full rounded-full bg-gradient-to-r from-cyan-300 to-violet-400" style={{ width: `${percentage}%` }}/></div></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1 text-xs text-slate-400">{label}{children}</label>; }
const inputClass = "rounded-lg border border-white/10 bg-white/[.04] px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-300/60";

export function PerformanceWorkspace({ initial }: { initial: PerformanceSnapshot }) {
  const [data, setData] = useState(initial); const [modal, setModal] = useState<"goal" | "challenge" | "achievement" | null>(null); const [editing, setEditing] = useState<PerformanceGoal | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function refresh() { setBusy(true); setError(""); try { const response = await fetch("/api/admin/performance"); const next = await response.json(); if (!response.ok) throw new Error(next.error); setData(next); } catch (cause) { setError(cause instanceof Error ? cause.message : "Falha ao atualizar."); } finally { setBusy(false); } }
  async function run(action: () => Promise<void>) { setBusy(true); setError(""); try { await action(); setModal(null); setEditing(null); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Operação não concluída."); } finally { setBusy(false); } }
  return <div className="space-y-6">{error && <div role="alert" className="rounded-xl border border-rose-400/30 bg-rose-400/10 px-4 py-3 text-sm text-rose-200">{error}</div>}<div className="flex flex-wrap gap-2"><button onClick={() => { setEditing(null); setModal("goal"); }} className="admin-primary-btn"><Plus size={15}/> Meta</button><button onClick={() => setModal("challenge")} className="admin-secondary-btn"><Plus size={15}/> Desafio</button><button onClick={() => setModal("achievement")} className="admin-secondary-btn"><Plus size={15}/> Conquista</button><button onClick={refresh} className="admin-icon-btn" aria-label="Atualizar performance"><RefreshCw size={16} className={busy ? "animate-spin" : ""}/></button></div>
    {!data.hasRealEvents && <div className="rounded-xl border border-amber-300/20 bg-amber-300/[.05] p-4 text-sm text-amber-100">Ainda não há eventos reais suficientes para pontuar a equipe. Crie metas e registre atividades no CRM, Inbox ou Financeiro para acompanhar progresso.</div>}
    <section className="grid gap-4 sm:grid-cols-3"><div className="admin-mini-stat"><span>Metas ativas</span><strong>{data.goals.filter((goal) => goal.status === "active").length}</strong><small>Individuais e equipe</small></div><div className="admin-mini-stat"><span>Desafios ativos</span><strong>{data.challenges.filter((challenge) => challenge.status === "active").length}</strong><small>Janela de resultado</small></div><div className="admin-mini-stat"><span>Conquistas obtidas</span><strong>{data.achievements.filter((achievement) => achievement.awardedToCurrentUser).length}</strong><small>Sem pontos artificiais</small></div></section>
    <div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><section className="admin-card"><div className="mb-5 flex items-center justify-between"><div><p className="admin-eyebrow">Performance / objetivos</p><h2 className="font-[var(--font-heading)] text-lg">Metas</h2></div><Target size={18} className="text-cyan-300"/></div>{data.goals.length === 0 ? <p className="text-sm text-slate-500">Nenhuma meta criada ainda.</p> : <div className="grid gap-3">{data.goals.map((goal) => <div key={goal.id} className="rounded-xl border border-white/[.07] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium text-slate-200">{goal.title}</p><p className="mt-1 text-xs text-slate-500">{metricLabels[goal.metric]} · {goal.ownerId ? "Individual" : "Equipe"} · até {goal.periodEnd}</p></div><button onClick={() => { setEditing(goal); setModal("goal"); }} className="admin-icon-btn" aria-label="Editar meta"><Edit3 size={14}/></button></div><div className="mt-3 flex items-end justify-between"><strong className="text-xl text-slate-100">{valueLabel(goal.metric, goal.currentValue)}</strong><span className="text-xs text-slate-500">de {valueLabel(goal.metric, goal.targetValue)}</span></div><ProgressBar metric={goal.metric} value={goal.currentValue} target={goal.targetValue}/></div>)}</div>}</section><section className="admin-card"><div className="mb-5 flex items-center justify-between"><div><p className="admin-eyebrow">Team / real events</p><h2 className="font-[var(--font-heading)] text-lg">Ranking</h2></div><span className="text-xs text-slate-500">Resultado acumulado</span></div>{data.ranking.length === 0 || !data.hasRealEvents ? <p className="text-sm text-slate-500">Ranking indisponível até existirem eventos reais de produção.</p> : <div className="grid gap-2">{data.ranking.map((member, index) => <div key={member.userId} className="flex items-center gap-3 rounded-lg border border-white/[.06] p-3"><span className="w-6 text-center text-xs text-slate-600">{index + 1}</span><span className="grid h-8 w-8 place-items-center rounded-full bg-cyan-300/10 text-xs text-cyan-200">{member.name.slice(0, 2).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="truncate text-sm text-slate-200">{member.name}</p><p className="text-[11px] text-slate-500">{member.dealsWon} negócios · {member.tasksCompleted} tarefas</p></div><strong className="text-sm text-cyan-200">{member.score}</strong></div>)}</div>}</section></div>
    <div className="grid gap-6 xl:grid-cols-2"><section className="admin-card"><div className="mb-5 flex items-center justify-between"><div><p className="admin-eyebrow">Team focus</p><h2 className="font-[var(--font-heading)] text-lg">Desafios</h2></div></div>{data.challenges.length === 0 ? <p className="text-sm text-slate-500">Nenhum desafio criado ainda.</p> : <div className="grid gap-3">{data.challenges.map((challenge) => <div key={challenge.id} className="rounded-xl border border-white/[.07] p-4"><p className="text-sm font-medium text-slate-200">{challenge.title}</p><p className="mt-1 text-xs text-slate-500">{metricLabels[challenge.metric]} · até {challenge.periodEnd}</p><ProgressBar metric={challenge.metric} value={challenge.currentValue} target={challenge.targetValue}/></div>)}</div>}</section><section className="admin-card"><div className="mb-5 flex items-center justify-between"><div><p className="admin-eyebrow">Recognition / evidence</p><h2 className="font-[var(--font-heading)] text-lg">Conquistas</h2></div><Trophy size={18} className="text-violet-300"/></div>{data.achievements.length === 0 ? <p className="text-sm text-slate-500">Nenhuma conquista definida ainda.</p> : <div className="grid gap-3">{data.achievements.map((achievement) => <div key={achievement.id} className={`rounded-xl border p-4 ${achievement.awardedToCurrentUser ? "border-emerald-300/20 bg-emerald-300/[.04]" : "border-white/[.07]"}`}><div className="flex items-start gap-3">{achievement.awardedToCurrentUser ? <Check className="mt-0.5 text-emerald-300" size={16}/> : <Trophy className="mt-0.5 text-slate-600" size={16}/>}<div><p className="text-sm text-slate-200">{achievement.title}</p><p className="mt-1 text-xs text-slate-500">{achievement.description}</p><p className="mt-2 text-[11px] text-slate-600">{valueLabel(achievement.metric, achievement.currentValue)} / {valueLabel(achievement.metric, achievement.targetValue)}</p></div></div></div>)}</div>}</section></div>
    {modal === "goal" && <GoalModal goal={editing} onClose={() => { setModal(null); setEditing(null); }} onSubmit={(payload) => void run(() => post(payload))}/>} {modal === "challenge" && <DefinitionModal title="Novo desafio" action="challenge.create" onClose={() => setModal(null)} onSubmit={(payload) => void run(() => post(payload))}/>} {modal === "achievement" && <DefinitionModal title="Nova conquista" action="achievement.create" onClose={() => setModal(null)} onSubmit={(payload) => void run(() => post(payload))}/>}</div>;
}

function ModalShell({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="w-full max-w-lg rounded-2xl border border-white/10 bg-[#0d0d20] p-6"><div className="mb-5 flex justify-between"><h2 className="font-[var(--font-heading)] text-lg">{title}</h2><button onClick={onClose} className="text-sm text-slate-500">Fechar</button></div>{children}</div></div>; }
function GoalModal({ goal, onClose, onSubmit }: { goal: PerformanceGoal | null; onClose: () => void; onSubmit: (payload: Record<string, unknown>) => void }) { return <ModalShell title={goal ? "Editar meta" : "Nova meta"} onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); onSubmit(goal ? { action: "goal.update", goalId: goal.id, title: form.get("title"), targetValue: Number(form.get("targetValue")), periodStart: form.get("periodStart"), periodEnd: form.get("periodEnd"), status: form.get("status") } : { action: "goal.create", title: form.get("title"), metric: form.get("metric"), targetValue: Number(form.get("targetValue")), periodStart: form.get("periodStart"), periodEnd: form.get("periodEnd"), scope: form.get("scope") }); }} className="grid gap-3"><Field label="Título"><input name="title" required defaultValue={goal?.title} className={inputClass}/></Field>{!goal && <><Field label="Métrica"><select name="metric" className={inputClass}>{Object.entries(metricLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="Escopo"><select name="scope" className={inputClass}><option value="individual">Minha meta</option><option value="team">Meta da equipe</option></select></Field></>}<Field label="Alvo"><input name="targetValue" type="number" min="1" required defaultValue={goal?.targetValue} className={inputClass}/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Início"><input name="periodStart" type="date" required defaultValue={goal?.periodStart ?? new Date().toISOString().slice(0, 10)} className={inputClass}/></Field><Field label="Fim"><input name="periodEnd" type="date" required defaultValue={goal?.periodEnd ?? new Date().toISOString().slice(0, 10)} className={inputClass}/></Field></div>{goal && <Field label="Status"><select name="status" defaultValue={goal.status} className={inputClass}><option value="active">Ativa</option><option value="archived">Arquivada</option></select></Field>}<button className="admin-primary-btn">Salvar meta</button></form></ModalShell>; }
function DefinitionModal({ title, action, onClose, onSubmit }: { title: string; action: "challenge.create" | "achievement.create"; onClose: () => void; onSubmit: (payload: Record<string, unknown>) => void }) { return <ModalShell title={title} onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); onSubmit(action === "challenge.create" ? { action, title: form.get("title"), metric: form.get("metric"), targetValue: Number(form.get("targetValue")), periodStart: form.get("periodStart"), periodEnd: form.get("periodEnd") } : { action, title: form.get("title"), description: form.get("description"), metric: form.get("metric"), targetValue: Number(form.get("targetValue")) }); }} className="grid gap-3"><Field label="Título"><input name="title" required className={inputClass}/></Field><Field label="Métrica"><select name="metric" className={inputClass}>{Object.entries(metricLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field>{action === "achievement.create" && <Field label="Descrição"><input name="description" required maxLength={300} className={inputClass}/></Field>}<Field label="Alvo"><input name="targetValue" type="number" min="1" required className={inputClass}/></Field>{action === "challenge.create" && <div className="grid gap-3 sm:grid-cols-2"><Field label="Início"><input name="periodStart" type="date" required className={inputClass}/></Field><Field label="Fim"><input name="periodEnd" type="date" required className={inputClass}/></Field></div>}<button className="admin-primary-btn">Salvar</button></form></ModalShell>; }
