"use client";

import { useState } from "react";
import { CheckCircle2, Link2, Plus, RefreshCw, Send, TriangleAlert } from "lucide-react";
import type { WhatsAppInstance } from "@/lib/whatsapp-types";

type Props = { initial: { instances: WhatsAppInstance[]; configurations: { provider: "official" | "unofficial"; configured: boolean; reason?: string }[] } };
async function post(payload: Record<string, unknown>) { const response = await fetch("/api/admin/whatsapp", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error ?? "Operação não concluída."); return body; }

export function WhatsAppWorkspace({ initial }: Props) {
  const [data, setData] = useState(initial); const [selected, setSelected] = useState<WhatsAppInstance | null>(initial.instances[0] ?? null); const [open, setOpen] = useState(false); const [provider, setProvider] = useState<"official" | "unofficial">("official"); const [name, setName] = useState(""); const [externalId, setExternalId] = useState(""); const [recipient, setRecipient] = useState(""); const [body, setBody] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function refresh() { const response = await fetch("/api/admin/whatsapp"); const next = await response.json(); if (!response.ok) throw new Error(next.error); setData(next); setSelected((current) => next.instances.find((item: WhatsAppInstance) => item.id === current?.id) ?? next.instances[0] ?? null); }
  async function run(action: () => Promise<unknown>) { setBusy(true); setError(""); try { await action(); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Operação não concluída."); } finally { setBusy(false); } }
  const config = data.configurations.find((item) => item.provider === provider);
  return <div className="space-y-6">
    {error && <div role="alert" className="rounded-xl border border-rose-400/30 bg-rose-400/10 px-4 py-3 text-sm text-rose-200">{error}</div>}
    <div className="grid gap-4 md:grid-cols-2">{data.configurations.map((item) => <div key={item.provider} className="admin-card"><div className="flex items-start justify-between"><div><p className="admin-eyebrow">Provider {item.provider === "official" ? "Meta Cloud API" : "Adapter externo"}</p><h2 className="mt-1 font-[var(--font-heading)] text-lg">WhatsApp {item.provider === "official" ? "Oficial" : "Não oficial"}</h2></div>{item.configured ? <CheckCircle2 className="text-emerald-300" size={20}/> : <TriangleAlert className="text-amber-300" size={20}/>}</div><p className="mt-3 text-xs text-slate-500">{item.configured ? "Credenciais disponíveis no servidor." : item.reason}</p></div>)}</div>
    <div className="flex flex-wrap gap-2"><button onClick={() => setOpen(true)} className="admin-primary-btn"><Plus size={15}/> Cadastrar instância</button><button onClick={() => void run(refresh)} className="admin-icon-btn" aria-label="Atualizar"><RefreshCw size={16} className={busy ? "animate-spin" : ""}/></button></div>
    <section className="grid gap-6 lg:grid-cols-[300px_1fr]"><aside className="admin-card p-0"><div className="border-b border-white/[.08] p-4"><p className="admin-eyebrow">Instances</p><h2 className="font-[var(--font-heading)] text-lg">Linhas cadastradas</h2></div>{data.instances.map((instance) => <button key={instance.id} onClick={() => setSelected(instance)} className={`w-full border-b border-white/[.06] p-4 text-left ${selected?.id === instance.id ? "bg-cyan-300/[.07]" : "hover:bg-white/[.03]"}`}><div className="flex justify-between gap-3"><span className="text-sm text-slate-200">{instance.name}</span><span className={`text-[10px] ${instance.status === "connected" ? "text-emerald-300" : "text-slate-500"}`}>{instance.status}</span></div><p className="mt-1 text-xs text-slate-500">{instance.provider} · {instance.phoneNumber || instance.externalId}</p></button>)}{!data.instances.length && <p className="p-5 text-sm text-slate-500">Nenhuma instância cadastrada.</p>}</aside><div className="admin-card min-h-[360px]">{selected ? <><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="admin-eyebrow">{selected.provider === "official" ? "Meta Cloud API" : "Provider não oficial"}</p><h2 className="font-[var(--font-heading)] text-xl">{selected.name}</h2><p className="mt-1 text-xs text-slate-500">ID externo: {selected.externalId}</p></div><button onClick={() => void run(async () => { await post({ action: "instance.check", instanceId: selected.id }); })} className="admin-secondary-btn"><Link2 size={14}/> Verificar conexão</button></div>{selected.lastError && <div className="mt-5 rounded-lg border border-amber-300/20 bg-amber-300/[.05] p-3 text-xs text-amber-200">{selected.lastError}</div>}<div className="mt-8 border-t border-white/[.08] pt-5"><p className="mb-3 text-sm text-slate-300">Enviar mensagem de teste</p><div className="grid gap-3 sm:grid-cols-[180px_1fr_auto]"><input value={recipient} onChange={(event) => setRecipient(event.target.value)} placeholder="5511999999999" className="rounded-lg border border-white/10 bg-white/[.04] px-3 py-2.5 text-sm text-white"/><input value={body} onChange={(event) => setBody(event.target.value)} placeholder="Mensagem" className="rounded-lg border border-white/10 bg-white/[.04] px-3 py-2.5 text-sm text-white"/><button disabled={!recipient || !body || busy} onClick={() => void run(async () => { await post({ action: "message.send", instanceId: selected.id, recipient, body }); setBody(""); })} className="grid h-10 w-10 place-items-center rounded-lg bg-cyan-300 text-[#050510] disabled:opacity-40" aria-label="Enviar"><Send size={15}/></button></div></div></> : <div className="grid h-full place-items-center text-center text-sm text-slate-500">Selecione uma instância para gerenciar.</div>}</div></section>
    {open && <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><form onSubmit={(event) => { event.preventDefault(); void run(async () => { await post({ action: "instance.create", provider, name, externalId }); setOpen(false); setName(""); setExternalId(""); }); }} className="w-full max-w-md rounded-2xl border border-white/10 bg-[#0d0d20] p-6"><div className="mb-5 flex justify-between"><h2 className="font-[var(--font-heading)] text-lg">Cadastrar instância</h2><button type="button" onClick={() => setOpen(false)} className="text-sm text-slate-500">Fechar</button></div><label className="grid gap-2 text-xs text-slate-400">Provider<select value={provider} onChange={(event) => setProvider(event.target.value as "official" | "unofficial")} className="rounded-lg border border-white/10 bg-[#15152a] px-3 py-2.5 text-sm text-white"><option value="official">WhatsApp Oficial / Meta</option><option value="unofficial">Provider não oficial</option></select></label><p className="mt-3 text-xs text-slate-500">{config?.configured ? "Credenciais configuradas." : config?.reason}</p><label className="mt-3 grid gap-2 text-xs text-slate-400">Nome<input required maxLength={100} value={name} onChange={(event) => setName(event.target.value)} className="rounded-lg border border-white/10 bg-white/[.04] px-3 py-2.5 text-sm text-white"/></label><label className="mt-3 grid gap-2 text-xs text-slate-400">{provider === "official" ? "Phone Number ID da Meta" : "ID da instância no provider"}<input required maxLength={200} value={externalId} onChange={(event) => setExternalId(event.target.value)} className="rounded-lg border border-white/10 bg-white/[.04] px-3 py-2.5 text-sm text-white"/></label><button className="mt-5 w-full rounded-xl bg-cyan-300 px-4 py-3 text-sm font-semibold text-[#050510]">Salvar instância</button></form></div>}
  </div>;
}
